### ISSUE TITLE
Clean["Global`"] breaks the communication

### ISSUE THREAD

**Issue by kkoudas01** [JerryI/wolfram-js-frontend#342]
The kernel freezes when I input a differential equation. Specifically, I write `dEqX := x'[t] == ax*(SX-x[t])(px-(x[t]-y[t])/y[t])`, press `shift+enter`, and then nothing happens. It seems like the execution progresses to about halfway and then stalls. Naturally, no other commands can be executed (I tried something like `1+1`) while this is happening.

I also tried restarting the kernel to interrupt the execution, but that didn't work either. I have to completely close the program to regain functionality. After restarting, I can execute some commands again.

Thank you in advance!

P.S.: My code shouldn't have any errors, as I tested it on Wolfram Cloud, and it works perfectly there.

**Comment by JerryI** [comment]
Hi! Could you, please, provide the full code?

I tested just this one

<img width="631" alt="Image" src="https://github.com/user-attachments/assets/a287156a-daac-4af1-a564-afec9e99c8f3" />

**Comment by kkoudas01** [comment]
The only thing I had written was **Clear["Global`*"]**:

```
Clear["Global`*"]
dEqX := x'[t] == ax*(SX-x[t])(px-(x[t]-y[t])/y[t])
dEqX
```

I tried running `dEqX` on its own when you responded, and it was OK. With `Clear["Global"]`, the same issue came up again. Could **Clear["Global`"]** be the problem?

**Comment by JerryI** [comment]
Yes, it kills some of the internal handlers, which are (for some reason) in the global scope

**Comment by JerryI** [comment]
Then the solution would be to clean only specific symbols

**Comment by kkoudas01** [comment]
I see. I didn’t expect that. I’ll keep it in mind! Thanks!

**Comment by JerryI** [comment]
Ok we found an issue. This is relatively an easy fix, but we need to make sure that everything is tested.

**Comment by JerryI** [comment]
Fixed in a new release

**Comment by kkoudas01** [comment]
First of all, thank you for your response!

Regarding the issue we are discussing, I installed the new version as recommended by the program itself and also performed an update. The problem I initially mentioned no longer exists; however, the command **Clear["Global*"]`** is still not functional, as shown in the attached image, as well as in the code below and its outputs.

![Image](https://github.com/user-attachments/assets/81732d98-32a9-4734-8640-cd814a8bdb8c)

**Input:**

```
a = 1+1;
a
Clear["Global`*"]
a
```

**Output:**

```
2
$Failed
2
```

**Comment by JerryI** [comment]
> First of all, thank you for your response!
> 
> Regarding the issue we are discussing, I installed the new version as recommended by the program itself and also performed an update. The problem I initially mentioned no longer exists; however, the command **Clear["Global*"]`** is still not functional, as shown in the attached image, as well as in the code below and its outputs.
> 
> ![Image](https://github.com/user-attachments/assets/81732d98-32a9-4734-8640-cd814a8bdb8c)
> 
> **Input:**
> 
> ```
> a = 1+1;
> a
> Clear["Global`*"]
> a
> ```
> 
> **Output:**
> 
> ```
> 2
> $Failed
> 2
> ```

Oh. It's another bug.
I tested on this, it should work

```
Clear /@ Names["Global`*"]
```

**Comment by kkoudas01** [comment]
Oh! I hope I am not bothering you with the reports of the errors I find. I thought that bringing them to your attention contributes to the improvement of your excellent work.
